### ISSUE TITLE
Add CodeQL code scanning

### ISSUE THREAD

**Issue by desertaxle** [PrefectHQ/prefect-collection-template#33]
Add configuration for CodeQL code scanning to the template os that collections can be set up with CodeQL code scanning out of the box. 

Here's the documentation for setting up CodeQL code scanning: https://docs.github.com/en/code-security/code-scanning/automatically-scanning-your-code-for-vulnerabilities-and-errors/setting-up-code-scanning-for-a-repository#setting-up-code-scanning-using-actions

**Comment by ahuang11** [comment]
I think this can be closed?
