### ISSUE TITLE
Why not pyproject.toml ?

### ISSUE THREAD

**Issue by davzucky** [PrefectHQ/prefect-collection-template#45]
I like the idea of having a template for creating the collections. As more and more python projects are moving to pyproject.toml, I'm wondering why not use that new project format for the template?

This would allow: 
- use more modern tools
- have all the configurations in one file
- better support for dependencies
- Enable lock file support

**Comment by desertaxle** [comment]
I'm going to close this issue since there hasn't been an activity for a while. @davzucky feel free to reopen if you plan on implementing something!
